//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class collection_fares
    {
        public int col_far_id { get; set; }
        public int reg_tra_id { get; set; }
        public int vau_wit_id { get; set; }
        public int usr_det_id { get; set; }
    
        public virtual register_travel register_travel { get; set; }
        public virtual vault_withdraws vault_withdraws { get; set; }
        public virtual user_details user_details { get; set; }
    }
}
