//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geo_zipcodes
    {
        public geo_zipcodes()
        {
            this.user_address = new HashSet<user_address>();
        }
    
        public int geo_zip_id { get; set; }
        public int geo_zip_code { get; set; }
        public string geo_zip_city { get; set; }
    
        public virtual ICollection<user_address> user_address { get; set; }
    }
}
