//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class register_date_type
    {
        public register_date_type()
        {
            this.register_travel = new HashSet<register_travel>();
        }
    
        public int reg_dat_typ_id { get; set; }
        public string reg_dat_typ_title { get; set; }
    
        public virtual ICollection<register_travel> register_travel { get; set; }
    }
}
