//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routing_zones
    {
        public routing_zones()
        {
            this.routing_zone_neighbors = new HashSet<routing_zone_neighbors>();
            this.transit_locations = new HashSet<transit_locations>();
        }
    
        public int rot_zon_id { get; set; }
        public int rot_opt_id { get; set; }
        public int rot_zon_area_id { get; set; }
        public bool rot_zon_active { get; set; }
    
        public virtual routing_operators routing_operators { get; set; }
        public virtual ICollection<routing_zone_neighbors> routing_zone_neighbors { get; set; }
        public virtual ICollection<transit_locations> transit_locations { get; set; }
    }
}
