//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routing_operators
    {
        public routing_operators()
        {
            this.routing_zones = new HashSet<routing_zones>();
        }
    
        public int rot_opt_id { get; set; }
        public int rot_opt_no { get; set; }
        public string rot_opt_title { get; set; }
        public string rot_opt_title_full { get; set; }
        public bool rot_opt_active { get; set; }
    
        public virtual ICollection<routing_zones> routing_zones { get; set; }
    }
}
