//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class routing_zone_neighbors
    {
        public int rot_zon_ngr_id { get; set; }
        public int rot_zon_id { get; set; }
        public int rot_zon_ngr_area { get; set; }
        public bool rot_zon_ngr_active { get; set; }
    
        public virtual routing_zones routing_zones { get; set; }
    }
}
