
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Repository.Models
{

using System;
    using System.Collections.Generic;
    
public partial class security_groups
{

    public security_groups()
    {

        this.security_credentials = new HashSet<security_credentials>();

    }


    public int sec_gro_id { get; set; }

    public string sec_gro_title { get; set; }

    public System.DateTime sec_gro_timestamp { get; set; }

    public bool sec_gro_active { get; set; }



    public virtual ICollection<security_credentials> security_credentials { get; set; }

}

}
