
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Repository.Models
{

using System;
    using System.Collections.Generic;
    
public partial class transit_locations
{

    public transit_locations()
    {

        this.register_travel = new HashSet<register_travel>();

    }


    public int tra_loc_id { get; set; }

    public int tra_typ_id { get; set; }

    public int rot_zon_id { get; set; }

    public int tra_loc_area_id { get; set; }

    public string tra_loc_title { get; set; }

    public bool tra_loc_active { get; set; }



    public virtual routing_zones routing_zones { get; set; }

    public virtual transit_type transit_type { get; set; }

    public virtual ICollection<register_travel> register_travel { get; set; }

}

}
