//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address
    {
        public int usr_adr_id { get; set; }
        public int usr_det_id { get; set; }
        public int geo_zip_id { get; set; }
        public string usr_det_street { get; set; }
    
        public virtual geo_zipcodes geo_zipcodes { get; set; }
        public virtual user_details user_details { get; set; }
    }
}
