//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    
    public partial class User
    {
        public string fname { get; set; }
        public string lname { get; set; }
        public string street { get; set; }
        public Nullable<int> zipcode { get; set; }
        public string city { get; set; }
        public byte[] ssn { get; set; }
        public Nullable<int> phoneno { get; set; }
        public string email { get; set; }
        public string sec_group { get; set; }
        public string uname { get; set; }
        public string passwd { get; set; }
        public Nullable<System.DateTime> created_timestamp { get; set; }
        public Nullable<bool> is_active { get; set; }
    }
}
