//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_details
    {
        public user_details()
        {
            this.card_issued = new HashSet<card_issued>();
            this.card_retracted = new HashSet<card_retracted>();
            this.vault_depositits = new HashSet<vault_depositits>();
            this.vault_withdraws = new HashSet<vault_withdraws>();
            this.register_travel = new HashSet<register_travel>();
        }
    
        public int usr_det_id { get; set; }
        public int sec_cre_id { get; set; }
        public string usr_det_fname { get; set; }
        public string usr_det_lname { get; set; }
        public byte[] usr_det_ssn { get; set; }
        public int usr_det_phoneno { get; set; }
        public string usr_det_email { get; set; }
        public System.DateTime usr_det_timestamp { get; set; }
        public bool usr_det_active { get; set; }
    
        public virtual ICollection<card_issued> card_issued { get; set; }
        public virtual ICollection<card_retracted> card_retracted { get; set; }
        public virtual security_credentials security_credentials { get; set; }
        public virtual ICollection<vault_depositits> vault_depositits { get; set; }
        public virtual ICollection<vault_withdraws> vault_withdraws { get; set; }
        public virtual ICollection<register_travel> register_travel { get; set; }
    }
}
